storelite/core/urls.py
from django.contrib import admin
from django.urls import path, include

# from django.conf import settings
# from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/', include('django.contrib.auth.urls')),
    path('store/', include('store.urls', namespace="store")),
    path('', include('public.urls', namespace='public')),
    path('', include('storelite.urls', namespace="storelite")),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

storelite/store/urls.py
from django.urls import path
from .views import StoreView

app_name = "store"

urlpatterns = [
    path("register/", StoreView.as_view(), name="register"),
]

storelite/storelite/urls.py
from django.urls import path
from . import views

app_name = "storelite"

urlpatterns = [
    path('', views.home, name='home'), 
]

storelite/product/models.py
from django.db import models
from django.contrib.auth.models import User
from store.models import Store

from uuid import uuid4
import os

def user_directory_path(instance, filename):
    ext = filename.split(".")[-1]
    filename = f"{uuid4()}.{ext}"
    return os.path.join('product_images', filename)

class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, verbose_name = "Usuário")
    store = models.ForeignKey(Store, on_delete=models.CASCADE, related_name="products", verbose_name = "Nome da Loja")
    name = models.CharField(max_length=100, unique=True, verbose_name = "Nome do Produto")
    description = models.TextField(verbose_name = "Descrição")
    photo = models.ImageField(upload_to=user_directory_path, verbose_name = "Foto")
    cost = models.DecimalField(max_digits=10, decimal_places=2, verbose_name = "Valor")
    stock = models.PositiveIntegerField(verbose_name = "Quantidade no Estoque")
    number = models.CharField(max_length=20, blank=True, null=True, verbose_name = "Número")
    size = models.CharField(max_length=20, blank=True, null=True, verbose_name = "Tamanho")

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = "Produto"
        verbose_name_plural = "Produtos"

class CartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name = "Usuário")
    store = models.ForeignKey(Store, on_delete=models.CASCADE, verbose_name = "Nome da Loja")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name = "Produto")
    quantity = models.PositiveIntegerField(default=1, verbose_name = "Quantidade")

    class Meta:
        unique_together = ("user", "product", "store")

    class Meta:
        verbose_name = "Carrinho"
        verbose_name_plural = "Carrinho"

    def __str__(self):
        return f"{self.product.name} ({self.quantity}) - {self.user.username}"

storelite/store/models.py
from django.db import models
from django.contrib.auth.models import User


from django.utils.text import slugify
from django.urls import reverse

from colorfield.fields import ColorField

from uuid import uuid4
import os

def user_directory_path(instance, filename):
    ext = filename.split(".")[-1]
    filename = f"{uuid4()}.{ext}"
    return os.path.join('store_images', filename)


class Store(models.Model):
    COLOR_CHOICES = [
        ("#0b2545", "Azul Profundo"),
        ("#e91e63", "Rosa Claro"),
        ("#3f51b5", "Azul Médio"),
        ("#fdd835", "Amarelo Claro"),
        ("#ffb74d", "Laranja Suave"),
        ("#ef5350", "Vermelho Suave"),
        ("#ba68c8", "Roxo Claro"),
        ("#4db6ac", "Verde Água"),
        ("#c62828", "Vermelho Pizzaria"),
        ("#2E4D38", "Verde Musgo Escuro"),
        ("#3A0B52", "Roxo Beringela"),
        ("#2e2e2e", "Grafite Escuro"),
        ("#7B1E1E", "Vermelho Vinho"),
        ("#8B4513", "Marrom Queimado"),
        ("#665c1e", "Mostarda Escura"),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True, null=True, verbose_name="Usuário")
    store = models.CharField(max_length=100, unique=True, verbose_name="Nome da Loja")
    cnpj = models.CharField(max_length=18, unique=True, null=True, verbose_name="CNPJ")

    layout = models.CharField(max_length=50, default="standard", verbose_name="Layout")
    logo = models.ImageField(upload_to=user_directory_path, blank=True, null=True, verbose_name="Logo")
    page = models.ImageField(upload_to=user_directory_path, blank=True, null=True, verbose_name="Imagem da Principal")
    main = models.TextField(blank=True, verbose_name="Texto Principal")
    draft = models.ImageField(upload_to=user_directory_path, blank=True, null=True, verbose_name="Imagem de Destaque")
    text = models.TextField(blank=True, verbose_name="Descrição Adicional")

    telephone = models.CharField(max_length=20, blank=True, verbose_name="Telefone")
    whatsapp = models.CharField(max_length=20, blank=True, verbose_name="WhatsApp")
    email = models.EmailField(blank=True, verbose_name="Email")

    slug = models.SlugField(unique=True, blank=True)
    primary_color = ColorField(
        max_length=7,
        choices=COLOR_CHOICES,
        default="#0b2545",
        verbose_name="Cor Primária"
    )

    def __str__(self):
        return self.store
    
    class Meta:
        verbose_name = "Loja"
        verbose_name_plural = "Loja"

    def save(self, *args, **kwargs):
        new_slug = slugify(self.store)
        if self.slug != new_slug:
            self.slug = new_slug
        super().save(*args, **kwargs)

    def get_store_url(self):
        if self.slug:
            return reverse("public:store_front", args=[self.slug])
        return "#"


class UserProfile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, verbose_name="Usuário")
    store = models.ForeignKey(Store, on_delete=models.CASCADE, null=True, verbose_name="Loja")
    telephone = models.CharField(max_length=20, blank=True, null=True, verbose_name="Telefone")
    email = models.EmailField(blank=True, verbose_name="Email")

    class Meta:
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"

    def __str__(self):
        return self.user.username

storelite/storelite/models.py
from django.db import models

# Create your models here.

storelite/store/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class FormStore(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({
                "class": "vTextField", 
            })

class FormUser(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

storelite/product/views.py
from django.shortcuts import render

# Create your views here.

storelite/store/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from .forms import FormStore
from django.contrib.auth.models import User, Group

class StoreView(CreateView):
    model = User
    form_class = FormStore
    template_name = "store/register.html"
    success_url = reverse_lazy("login")

    def form_valid(self, form):
        user = form.save(commit=False)

        user.is_staff = True
        user.save()

        grupo, criado = Group.objects.get_or_create(name="STORE")
        user.groups.add(grupo)

        self.object = user

        return super().form_valid(form)

storelite/storelite/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'storelite/home.html')

storelite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}{{ store.store }} | StoreLite{% endblock %}</title>
    <link rel="icon" href="{{ store.logo.url }}" type="image/svg+xml" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css"/>
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}" />
    <link rel="stylesheet" href="{% url 'public:theme_css' store.slug %}">

  </head>

  <body>

    {% comment %} HEADER {% endcomment %}
    <header class="header-bg">
      <div class="header container">

        {% comment %} LOGO {% endcomment %}
        <a href="{% url 'public:store_front' store.slug %}"><img src="{{ store.logo.url }}" alt="Logo da Loja" class="logo" /></a>
        
        <button id="btn-menu" class="menu-icon" aria-label="Abrir menu">
          <i class="bi bi-list"></i> 
        </button>

        {% comment %} MENU {% endcomment %}
        <nav class="nav font-1" id="menu">
          <ul>
    
            <li><a href="{% url 'public:store_products' store.slug %}">Produtos</a></li>

            {% comment %} USUÁRIO LOGADO {% endcomment %}
            {% if user.is_authenticated %}
            <li><a href="{% url 'public:user_cart' store.slug %}"><i class="bi bi-bag-plus-fill"></i></a></li>
            <li><a href="{% url 'public:user_profile' store.slug %}"><i class="bi bi-person-circle"></i></a></li>

            <li>
              <form action="{% url 'public:user_logout' store_name=store.slug %}" method="post">
                {% comment %} SEGURANÇA {% endcomment %}
                {% csrf_token %}
                <button type="submit"><i class="bi bi-box-arrow-right font-1"></i></button>
              </form>
            </li>
            {% else %}
            {% comment %} USUÁRIO NÃO LOGADO {% endcomment %}
            <li>
              <a href="{% url 'public:client_login' store.slug %}"><i class="bi bi-person-circle"></i></a>
            </li>
            {% endif %}
          </ul>
        </nav>

      </div>
    </header>

    <main>{% block content %} {% endblock %}</main>

    {% comment %} FOOTER {% endcomment %}
    <footer class="footer-bg font-2">
      <div class="footer container">

        {% comment %} INFORMACOES {% endcomment %}
        <ul>
          <li><h2>Contato</h2></li>
          <li><a href="mailto:{{ store.email }}"><i class="bi bi-envelope-fill"></i>{{ store.email }}</a></li>
          <li><a href="tel:{{ store.telephone }}"><i class="bi bi-telephone-fill"></i>{{ store.telephone }}</a></li>
          <li><a href="https://wa.me/{{ store.whatsapp }}"><i class="bi bi-whatsapp"></i>{{ store.whatsapp }}</a></li>
        </ul>

        <img src="{{ store.logo.url }}" alt="Logo da Loja" class="logo" />

        {% comment %} COPY {% endcomment %}
        <p>© 2025 - {{ store.store }} | StoreLite. Todos os direitos reservados.</p>

      </div>
    </footer>

    <script src="{% static 'js/script.js' %}"></script>
    
  </body>
</html>

storelite/templates/base_home.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>StoreLite - Crie sua loja virtual</title>
    <link rel="icon" href="{% static 'img/logo.svg' %}" type="image/svg+xml" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css"/>
    <link rel="stylesheet" href="{% static 'css/home/home.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}" />

  </head>

  <body>

    <header class="header-bg">
      <div class="header container">
        <a href="{% url 'storelite:home'%}"><img src="{% static 'img/storelite.png' %}" alt="Logo da Loja" class="logo" /></a>
        
        <button id="btn-menu" class="menu-icon" aria-label="Abrir menu">
          <i class="bi bi-list"></i> 
        </button>

        <nav class="nav font-1" id="menu">
          <ul>
            <li><a href="{% url 'store:register' %}">Cadastrar</a></li>
            <a href="{% url 'login' %}">Logar</a>
          </ul>
        </nav>

      </div>
    </header>

    <main>{% block content %} {% endblock %}</main>

    <footer class="footer-bg font-2">
      <div class="footer container">
        <ul>
          <li><h2>Contato</h2></li>
          <li><a href="mailto:storelite@gmail.com"><i class="bi bi-envelope-fill"></i>storelite@gmail.com</a></li>
          <li><a href="tel:1199990000"><i class="bi bi-telephone-fill"></i>11 9999-0000</a></li>
          <li><a href="https://wa.me/11999990000"><i class="bi bi-whatsapp"></i>11 9 9999-0000</a></li>
        </ul>

        <img src="{% static 'img/storelite.png' %}" alt="Logo da Loja" class="logo" />

        <p>© 2025 - StoreLite. Todos os direitos reservados.</p>

      </div>
    </footer>

    <script src="{% static 'js/script.js' %}"></script>
    
  </body>
</html>

storelite/templates/store/register.html
{% extends "base_home.html" %} 
{% block content %}

<div class="register container">
  <div>
    <div class="welcome">
      <h2>Seja bem-vindo!</h2>
      <p>Já possui usuário?
        <a href="{% url 'login'%}">
          Login <i class="bi bi-arrow-up-right-square"></i>
        </a>
      </p>
    </div>

    <form method="post" novalidate>
      <h1 class="font-4">Cadastro</h1>
      
      <div class="register-item">
        
        {% csrf_token %}
        {% if form.non_field_errors %}
          <div class="form-errors">
            {% for error in form.non_field_errors %}
              <p class="error">{{ error }}</p>
            {% endfor %}
          </div>
        {% endif %}

        {% for field in form %}
          <div class="form-group">
            {{ field.label_tag }}
            {{ field }}
            {% if field.errors %}
              {% for error in field.errors %}
                <p class="error">{{ error }}</p>
              {% endfor %}
            {% endif %}
          </div>
        {% endfor %}
      </div>


      <button type="submit">Cadastrar</button>
    </form>
  </div>
</div>

{% endblock %}

storelite/templates/storelite/home.html
{% extends "base_home.html" %} {% block content %}
{% load static %}

  <section class="draft container">
    <img src="{% static '/img/storelite.png' %}" alt="Logo StoreLite">
    <div>
        <h1 class="font-4">Crie sua loja virtual em minutos.</h1>
        <p class="font-3">StoreLite é a solução rápida e gratuita para pequenos lojistas venderem online. Você só precisa se cadastrar e começar.</p>
        <a class="home" href="{% url 'store:register' %}">Comece agora</a>
    </div>
  </section>

  <section class="public-bg">

  <div class="public container">
    <h1 class="font-4">Lojas (Demo)</h1>
    <ul>
      <li>
        <img src="" />
        <h2 class="font-5"></h2>
        <p class="font-2"></p>
        <a href="#">Ver mais</a>
      </li>
        <li>
            <img src="" />
            <h2 class="font-5"></h2>
            <p class="font-2"></p>
            <a href="#">Ver mais</a>
        </li>
        <li>
            <img src="" />
            <h2 class="font-5"></h2>
            <p class="font-2"></p>
            <a href="#">Ver mais</a>
        </li>
    </ul>
  </div>

</section>

{% endblock %}